version: "3.8"

services: 
  web:
    build: .
    ports: 
      - 8080:80
    volumes:
      - ./dist/main.css:/usr/share/nginx/html/dist/main.css
      - ./src/index.html:/usr/share/nginx/html/index.html

# you can run theese locally to dev on this docker-compose file
# npm install -D tailwindcss
# npx tailwindcss -i ./src/main.css -o ./dist/main.css --watch 